# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=4000)),
                ('content', models.TextField()),
                ('status', models.PositiveSmallIntegerField()),
                ('url', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('tag', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('order', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('author', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('last_updated_date', models.DateTimeField(verbose_name='date updated')),
                ('isdeleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('status', models.PositiveSmallIntegerField()),
                ('order', models.FloatField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('last_updated_date', models.DateTimeField(verbose_name='date updated')),
                ('isdeleted', models.BooleanField()),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost')),
            ],
        ),
    ]
